version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: GoBarber
      MYSQL_USER: gobarber
      MYSQL_PASSWORD: gobarber
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
